### ISSUE TITLE
aflgo can fuzz LAVA-M 

### ISSUE THREAD

**Issue by noobLei** [aflgo/aflgo#101] opened 2021-09-10 11:47 UTC
hello，I want to fuzz LAVA-M with aflgo, Can I do that?   Have you ever done that? If you do , you can give me some advice. thanks

**Comment by mboehme** [comment] 2021-09-10 12:05
Closing this as not a bug. If you have a specific issue, please have a look at the existing issues and raise a new one if it doesn't exist yet.

**Closed by mboehme** 2021-09-10 12:05 UTC

**Comment by mboehme** [comment] 2021-09-10 12:07
(Everyone who wants to share their experience is welcome to do so, of course)

**Comment by noobLei** [comment] 2021-09-10 12:11
ok, it is my fault，I was just wondering if AFLGO could fuzz LAVA-M

**Comment by noobLei** [comment] 2021-09-10 12:12
ok, it is my fault，I was just wondering if AFLGO could fuzz LAVA-M


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflgo/aflgo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aflgo/aflgo] aflgo can fuzz LAVA-M  (#101)





 
(Everyone who wants to share their experience is welcome to do so, of course)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mboehme** [comment] 2021-09-10 12:16
No worries. It's good that you ask. However, with our limited resources, we can't track it as a bug or a feature request. Maybe you try yourself first and see if there is anything we need to fix in AFLGo

**Comment by noobLei** [comment] 2021-09-10 12:24
If aflgo can't track LAVA-M as a bug or a feature request,&nbsp;&nbsp;So maybe there's no difference between using AFL and AFLGo to fuzz LAVA-M.&nbsp;That's just my guess，I am not sure.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflgo/aflgo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aflgo/aflgo] aflgo can fuzz LAVA-M  (#101)





 
No worries. It's good that you ask. However, with our limited resources, we can't track it as a bug or a feature request. Maybe you try yourself first and see if there is anything we need to fix in AFLGo
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mboehme** [comment] 2021-09-10 15:25
In terms of setup, for AFLGo you would need to compile twice. Once to generate the CFGs and CG and to derive the distance information and once to instrument the distance information.

**Comment by noobLei** [comment] 2021-09-11 02:20
hello, I get the error in the picture when I use&nbsp; the command: $AFLGO/scripts/gen_distance_fast.py $SUBJECT $TMP_DIR xmllint follow the steps. So , how I should solve it? thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflgo/aflgo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aflgo/aflgo] aflgo can fuzz LAVA-M  (#101)





 
In terms of setup, for AFLGo you would need to compile twice. Once to generate the CFGs and CG and to derive the distance information and once to instrument the distance information.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
