### ISSUE TITLE
LAVA-M

### ISSUE THREAD

**Issue by LingXinL** [aflgo/aflgo#47] opened 2019-08-28 06:32 UTC
Hello, I would like to know if the LAVA data set problem has been resolved, whether there is a way to use, thank you

**Comment by thuanpv** [comment] 2019-08-29 01:50
Hi LingXinL,
As you know, in our CCS'17 paper we did not evaluate the AFLGo on the LAVA benchmark. If you could send me the steps you followed to set up the benchmark and the exact issue(s) you have faced, I would spend some time to find the root cause and resolve it for you.

**Comment by thuanpv** [comment] 2019-11-17 22:34
Close this as no more information is provided.

**Closed by thuanpv** 2019-11-17 22:34 UTC
