### ISSUE TITLE
When the target is reached

### ISSUE THREAD

**Issue by valour01** [aflgo/aflgo#33] opened 2018-08-06 11:19 UTC
I follow the tutorial on and fuzzed the xmllint for about 15hours.

However, how can I know whether the target is reached or not. How many inputs will hit the target? When is the first input that reaches the target generated

**Comment by mboehme** [comment] 2018-08-06 15:31
Closed as duplicate of #19 .

**Closed by mboehme** 2018-08-06 15:31 UTC
